feat: add clean arquitecture and SOLID patterns
dnieto-telefonica/testProject pull request #1
Opened 2022-07-13 14:19 UTC by dnieto-telefonica

In this commit the entire application has been refactored to satisfy the requirements of Clean Arquitecture and Model View Presenter. In addition to complying with different sections of the SOLID principles

2022-07-14 11:35 UTC, victorvmp commented
🍺  (Usamos la cerveza para comentarios que no son bloqueantes, son simplemente recomendaciones, tu eliges si las aplicas o no)

Te recomiendo que añadas al proyecto in .gitignore para evitar que se suban al repositorio código autogenerado, con este cambio evitarías cierto ruido que se añade a la revisión. 

Solo hay que hacerlo 1 vez, en el primer commit de cada proyecto.

Hay herramientas online que ayudan a construirlo si le proporcionas con que tecnología, IDE y herramientas vas a trabajar -> 
Me gusta mucho esta [gitignore.io](https://www.toptal.com/developers/gitignore/)

Si añades los tags: AndroidStudio, Android, Gradle, hace magia

2022-07-14 11:38 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/MainActivity.kt
> +class MainActivity : AppCompatActivity(), IMainActivityView {
🍺  el prefijo `I` en las interfaces era un estándar en Java hace tiempo, y las implementaciones se le añadían el sufijo `Impl`.  Nosotros solemos evitarlos, preferimos buscar un nombre de interfaz simple, sin la I, sobre todo en estos casos donde solo hay 1 implementación, que es una activity, con su nombre estándar

2022-07-14 11:53 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/databases/LocalStorage.kt
> +    override fun getUsers(): MutableList<User> {
En Interfaces, intenta siempre devolver el tipo más restrictivo, si propagas por todas tus capas una lista mutable, cualquiera en tu código en cualquier capa podría manipularlo (creo es lo que nos estaba pasando el otro día)

En este caso, devuelve `List<User` que es la abstracción de kotlin para list que es NO MUTABLE

2022-07-14 11:59 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/dialogs/EditTextDialog.kt
> +        fun newInstance(presenter: MainActivityPresenter, myStorage: IStorage): EditTextDialog {
Este diálogo o fragmento, comparte las mismas particularidades y restricciones de vida que puede tener una activity, esto hace que tengamos que tener especial cuidado en que cosas que proporcionan por constructor, ya que podrían producirse Memory Leak.

Un memory leak no deja de ser un objeto en memoria que no puede eliminarse por que tienen referencias a otros objetos que impiden su liberación. En este caso particular, el fragmento estaría guardando una referencia de la vista (Activity) a través del presenter.

Como regla general, evita provisionar dependencias por constructor a "cualquier" componente de UI de Android.

2022-07-14 12:04 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentBlank.kt
>              dialog.show(supportFragmentManager, "editDescription")
el fragment manager debería estar accesible a través de la referencia a la activity que tiene el fragmento en si, puedes comprobarlo?

2022-07-14 12:07 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentDisplay.kt
> +    mainActivityViewP: IMainActivityView,
Los fragmentos ya tienen una referencia a la activity que los "hostea" no es necesario provisionar esto por el constructor

2022-07-14 12:09 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentDisplay.kt
> +    bundleP: Bundle)
El bundle de datos de un fragmento se proporciona por parámetro, digamos que en la API del fragmento ya se ofrece un método para setear un Bundle de datos.

Te recomiendo revisar en [la docu de Android](https://developer.android.com/reference/android/app/Fragment), como recomiendan el paso de argumentos ->

2022-07-14 12:15 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/interactors/AddUserUseCase.kt
> +class AddUserUseCase() : Fragment(), IAddUserUseCase {
Una de los propósitos de usar arquitecturas limpias (u otras) es potenciar y facilitar la testabilidad de tus objetos, en Android, cuando más acoplado esté tu objeto al framework de Android, más dificil es hacer el unit testing.

Una regla de oro, que puedes aplicar en el 98% de las ocasiones, es que en tus objetos/clases de la capa de dominio, no haya referecias a clases de Android.

Hay excepciones, ya las veremos.

Por lo tanto, eliminaría que el caso de uso extiende de Fragment

2022-07-14 12:15 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/interactors/AddUserUseCase.kt
> +class AddUserUseCase() : Fragment(), IAddUserUseCase {
Igual para el resto de casos de uso

2022-07-14 12:16 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/interfaces/IStorage.kt
> +    fun getUsers(): MutableList<User>
🍺  en interfaces/contratos de clase, siempre devolver el tipo más restrictivo, en este caso una lista NO mutable : `List<User>`

2022-07-14 12:19 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/views/IMainActivityView.kt
> +    fun onSelectUser(bundle: Bundle)
Todos estos métodos `on` son acciones de usuario, deberían ser parte del presenter

![image](https://user-images.githubusercontent.com/5062911/178980694-cb29f48a-df92-41b9-a3fd-d583d9571d87.png)

2022-07-14 12:20 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentDisplay.kt
> +        var position: Int = bundle.getInt("position")
🍺  Tu objeto User es serializable, podrías guardarlo como dato serializado dentro dle Bundle y evitar la deserialización parámetro a parámetro

2022-07-14 12:25 UTC, victorvmp requested changes
Enorme curro @dnieto-telefonica ! Es impresionante lo que has conseguido en tan poco tiempo 💪 

Acabo de terminar la primera revisión, pls revisa los comentarios que te he puesto, alguno de ellos aplica a varias clases, he intentado no repetirme.

Gracias!

2022-07-14 14:19 UTC, dnieto-telefonica commented on app/src/main/java/com/example/fragmentstest/interactors/AddUserUseCase.kt
> +class AddUserUseCase() : Fragment(), IAddUserUseCase {
Se me debieron colar al copiar y pegar las clases de Kotlin 😅😂

2022-07-18 07:10 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentBlank.kt
> +class FragmentBlank(val myStorage: Storage) : Fragment() {
Recuerda evitar proporcionar parámetros en el constructor en fragmentos, solo datos que puedas pasar como argumentos serializados en los argumentos del fragmento

2022-07-18 07:11 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/dialogs/EditTextDialog.kt
> +        fun newInstance(myStorage: Storage): EditTextDialog {
El storage lo podrías inicializar en el propio fragmento, evita construirlo con dependencias complejas que puedan provocar leaks

2022-07-18 07:13 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/fragments/FragmentDisplay.kt
> +    val user: User,
⚠️ con construir los fragmentos pasandole datos por constructor sin serializar, en el caso de tu aplicación lo mismo no te encuentras con problemas, pero para que tu fragmento sea resiliente a cambios en su ciclo de vida: rotacciones, destrucciones etc etc. los datos deben estar serializados en los argumentos del fragmento cuando se crea su instancia

2022-07-18 07:15 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/interactors/AddUserUseCase.kt
> +    override fun addUser(myStorage: Storage, user: User) {
Storage, podría ser un parámetro del constructor de tu caso de uso, de esa forma se "invierte la dependencia" podrías tener N implementaciones del caso de uso, con distintos approaches de almacenamiento

2022-07-18 07:17 UTC, victorvmp reviewed
Gracias por aplicar todo el feedback!

Te he dejado un par de comentarios sobre el paso de datos a fragmentos así como una propuesta para que el contrato de tus casos de uso no estén acoplados a un Store, y que puedas provisionar esa dependencia por constructor para conseguir la "inversión" de dependencias

2022-07-18 07:19 UTC, victorvmp commented on app/src/main/java/com/example/fragmentstest/models/CustomAdapter.kt
> +    private val mainActivityView: IMainActivityView
Es posible que se te haya pasado subir este cambio?

2022-07-18 12:00 UTC, merged